import streamlit as st

from core import config, services, theme

try:
    meta = services.get_predictor().meta
except Exception:
    st.error("The model information could not be loaded. Please try again later.")
    st.stop()

ds, sp, mo = meta["dataset"], meta["split"], meta["model"]
labels = meta["class_labels"]
classes = [str(c) for c in meta["classes"]]
cc = ds["class_counts"]
d = config.DEFAULT_INPUTS

theme.page_header("About", "Project documentation: problem, data, preprocessing, model and how the app fits together.")

theme.card(
    "Problem",
    "<p>Diabetes is a chronic condition that is frequently diagnosed late. This project asks a practical question: "
    "given a handful of health indicators a person already knows (body-mass index, age group, blood pressure, "
    "cholesterol, general health, smoking, activity, history of stroke or heart disease, difficulty walking), "
    "can a model tell whether the pattern resembles <b>no diabetes</b>, <b>pre-diabetes</b> or <b>diabetes</b>? "
    "It is a three-class classification problem on survey data, built for learning and demonstration — not for diagnosis.</p>",
    kicker="Why",
)

theme.card(
    "Dataset",
    f"<p>The app uses <code>{theme.e(ds['file'])}</code>: <b>{ds['rows']:,} records</b> and {ds['columns']} columns "
    f"({ds['input_columns']} input columns plus two target columns, <code>Diabetes_012</code> and <code>Diabetes_Status</code>). "
    "The project README describes the source as the BRFSS 2015 diabetes health-indicators data "
    "(original file <code>diabetes_012_health_indicators_BRFSS2015.csv</code>); this is a cleaned version that adds readable "
    "label columns (for example BMI category, age category, gender, education and income level) next to the numeric codes.</p>"
    "<ul>"
    + "".join(f"<li><b>{theme.e(labels[c])}</b> (code {c}): {cc[c]:,} records ({cc[c] / ds['rows'] * 100:.1f}%)</li>" for c in classes)
    + "</ul>",
    kicker="Data",
)

theme.card(
    "Data preprocessing",
    "<ul>"
    "<li>Drop the two target columns from the inputs; the numeric <code>Diabetes_012</code> is the label.</li>"
    f"<li>One-hot encode the categorical (text) columns with <code>pandas.get_dummies</code>: {ds['input_columns']} input columns become "
    f"<b>{ds['model_features']} model features</b>. The feature order is stored with the model and always reused.</li>"
    f"<li>Stratified {int((1 - sp['test_size']) * 100)}/{int(sp['test_size'] * 100)} train/test split, <code>random_state={sp['random_state']}</code>.</li>"
    "<li>No scaling and no imputation: the model is tree-based, and the project code applies neither.</li>"
    "</ul>"
    "<p><b>At prediction time</b> the app repeats the same encoding for one person: height and weight become BMI, the age group becomes "
    "its dataset code, and every one-hot column is rebuilt from the numeric codes using mappings read directly from the dataset "
    "(each text label is a one-to-one function of its code).</p>",
    kicker="Preparation",
)

theme.card(
    "Machine learning",
    f"<p>A <b>Random Forest classifier</b> (scikit-learn) with {mo['params']['n_estimators']} trees, unlimited depth and "
    f"<code>class_weight=\"{mo['params']['class_weight']}\"</code> to counter class imbalance. It predicts one of the three classes and "
    "also exposes class probabilities (the share of trees voting for each class). The AI explanation and follow-up chat are generated by "
    "Google Gemini from the model's result and the answers you gave; Gemini does not change the prediction.</p>",
    kicker="Model",
)

st.subheader("Application workflow")
theme.flow(
    [
        ("User input", "answers in the assistant"),
        ("Existing chatbot", "original HTML · CSS · JavaScript, embedded unchanged"),
        ("Data preprocessing", "BMI, age code, one-hot features, fixed defaults"),
        ("Machine learning model", "trained Random Forest"),
        ("Prediction", "class + class probabilities"),
        ("Result", "shown in the chatbot with an AI explanation"),
    ]
)

theme.card(
    "Inputs and defaults",
    "<p>The assistant asks 11 questions. The model needs more inputs, so the remaining ones use fixed values carried over from the "
    "original backend: "
    f"cholesterol check = {int(d['CholCheck'])}, fruits = {int(d['Fruits'])}, vegetables = {int(d['Veggies'])}, "
    f"heavy alcohol = {int(d['HvyAlcoholConsump'])}, any healthcare = {int(d['AnyHealthcare'])}, "
    f"could not see a doctor because of cost = {int(d['NoDocbcCost'])}, bad mental-health days = {int(d['MentHlth_Days'])}, "
    f"bad physical-health days = {int(d['PhysHlth_Days'])}, sex = {int(d['Sex'])} (female in the dataset), "
    f"education level = {int(d['Education'])}, income level = {int(d['Income'])}. "
    "Treat results as an illustration of the model, not a personal assessment.</p>",
    kicker="Transparency",
)

theme.card(
    "Technologies",
    theme.chips(
        ["Python", "Pandas", "NumPy", "Scikit-learn", "Streamlit", "HTML", "CSS", "JavaScript", "Google Gemini (google-genai)", "Jupyter / Matplotlib (analysis notebook)"]
    ),
    kicker="Stack",
)
